### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by olliejm** [egorpavlikhin/Serilog.Sinks.Logtail#1]
Should this still be functional? I just tried to use it but saw nothing appear in Logtail, I'm pretty sure it was configured correctly

```cs
// Program.cs
builder.Host.UseSerilog((ctx, lc) =>
{
  lc.WriteTo.Console();
  lc.WriteTo.LogtailSink(sourceToken);
});
```

**Comment by nicoarm93** [comment]
Hi, the problem with this implementation is in the `LogtailSink` extension method where important properties are initialized outside the constructor but the Logtail classes are all initialized inside the constructor, so Logtail is missing a lot of parameters.
I have changed the method to this 
`public static LoggerConfiguration LogtailSink(
        this LoggerSinkConfiguration loggerConfiguration,
        string sourceToken,
        IFormatProvider? formatProvider = null,
        string endpoint = "https://in.logtail.com",
        int retries = 10,
        int flushPeriodMilliseconds = 250,
        int maxBatchSize = 1000)
    {
        return loggerConfiguration.Sink(new LogtailSink(formatProvider, sourceToken, endpoint, retries, flushPeriodMilliseconds, maxBatchSize));
    }`
and now is working.
